apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: |
    An Express.js application with Docker support.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: strivly/${{ values.name }}
    lighthouse.com/website-url: https://backstage.io
    backstage.io/adr-location: docs/adrs
  tags:
    - express
    - docker
    - nodejs
spec:
  type: service
  lifecycle: production
  owner: team-devops
